# Generated by Django 3.2.5 on 2021-07-05 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 17, 44, 43, 211896, tzinfo=utc)),
        ),
    ]
