# Generated by Django 3.2.5 on 2021-07-05 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20210705_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 20, 16, 59, 657834, tzinfo=utc)),
        ),
    ]
